export const cartas = [
  { name: "English", rare: 1, time: "2 minutes" },
  { name: "Jugamos Fall Guys", rare: 1, time: "1h" },
  { name: "Jugamos Overwatch", rare: 1, time: "1h" },
  { name: "Jugamos WZ", rare: 1, time: "1h" },
  { name: "Jugamos Suika", rare: 1, time: "1h" },
  { name: "Te cuento un chiste", rare: 1, time: null },
  { name: "Te hago un piropo", rare: 1, time: null },
  { name: "Te modelo", rare: 1, time: null },
  { name: "10 sentadillas", rare: 1, time: null },
  { name: "5 vueltas coreanas", rare: 1, time: null },
  { name: "Medio shot", rare: 1, time: null },
  { name: "Baile de TikTok", rare: 1, time: null },
  { name: "Un baile de mochipoints", rare: 1, time: null },
  { name: "Escoge un accesorio", rare: 1, time: null },
  { name: "Te doy un consejo", rare: 1, time: null },
  { name: "Haces una encuesta", rare: 1, time: null },
  { name: "Jugamos Fortnite", rare: 1, time: "1h" },
  { name: "Zing random", rare: 1, time: null },
  { name: "Te hago un wallpaper", rare: 1, time: null },
  { name: "Intento de karaoke", rare: 1, time: null },
  { name: "Te coqueteo?", rare: 1, time: null },
  { name: "2 verdades 1 mentira", rare: 1, time: null },
  { name: "Horóscopo", rare: 1, time: null },
  { name: "Escoge un tweet", rare: 1, time: null },
  { name: "Termino las frases con una palabra", rare: 1, time: null },
  { name: "Exagero todo", rare: 1, time: null },
  { name: "Positivismo", rare: 1, time: "2min" },
  { name: "Te dedico una Canción", rare: 1, time: null },
  { name: "5 abdominales", rare: 1, time: null },
  { name: "Mirada juzgona", rare: 1, time: null },
  { name: "Mirada creepy", rare: 1, time: null },
  { name: "Escoge un acento", rare: 1, time: null },
  { name: "Jugamos kart rider", rare: 1, time: "1h" },
  { name: "Carta caritativa", rare: 1, time: null },
  { name: "Me automuero en el juego", rare: 1, time: null },
  { name: "Voz vato", rare: 1, time: "2 min" },
  { name: "Baile bombom", rare: 1, time: null },
  { name: "Me tomo un SHOT", rare: 2, time: null },
  { name: "English con acento paisa", rare: 2, time: "2min" },
  { name: "Te sigo en alguna red social", rare: 2, time: null },
  { name: "Perreo gracioso", rare: 2, time: null },
  { name: "Canción de just dance", rare: 2, time: null },
  { name: "Videozing", rare: 2, time: null },
  { name: "Selfie graciosa", rare: 2, time: null },
  { name: "Bailo YMCA", rare: 2, time: null },
  { name: "Bailo Gangnam style", rare: 2, time: null },
  { name: "Medio limón", rare: 2, time: null },
  { name: "Hula Hula", rare: 2, time: "30 segundos" },
  { name: "Pongo la quemona", rare: 2, time: null },
  { name: "Selfie bonita para ti", rare: 2, time: null },
  { name: "Te mando un audio bonito", rare: 2, time: null },
  { name: "English - Con acento paisa", rare: 2, time: null },
  { name: "Baile de los pingüinos", rare: 2, time: null },
  { name: "30 sentadillas", rare: 2, time: null },
  { name: "Baile kpop", rare: 2, time: null },
  { name: "Denegar algo del juego", rare: 2, time: null },
  { name: "Crear comando", rare: 2, time: null },
  { name: "Jugamos xdefiant", rare: 2, time: "1h" },
  { name: "Verdad o Reto", rare: 2, time: null },
  { name: "Doctora corazón", rare: 2, time: null },
  { name: "Insulto tierno", rare: 2, time: null },
  { name: "Chismoseo tus redes sociales", rare: 2, time: null },
  { name: "Voz kawai", rare: 2, time: "2 min" },
  { name: "Voz ardilla", rare: 2, time: "2 min" },
  { name: "Te hago un wallpaper", rare: 2, time: null },
  { name: "Intento de origami", rare: 2, time: null },
  { name: "Intento una figura en plastilina", rare: 2, time: null },
  { name: "Juego con manos cruzadas", rare: 2, time: null },
  { name: "Te dedico un poema", rare: 2, time: null },
  { name: "Opinión sincera", rare: 2, time: null },
  { name: "Ara Ara", rare: 2, time: null },
  { name: "Fijar un mensaje", rare: 2, time: null },
  { name: "Adivina la canción 5seg", rare: 2, time: null },
  { name: "Juego que escojas", rare: 2, time: null },
  { name: "Cámbiame space por letra de elección", rare: 2, time: null },
  { name: "Actuo y hablo en camara lenta - Flash", rare: 2, time: null },

  { name: "Jugamos LOL", rare: 3, time: "1h" },
  { name: "Te digo papacito", rare: 3, time: null },
  { name: "Escoge un cosplay", rare: 3, time: null },
  { name: "Te dibujo", rare: 3, time: null },
  { name: "Futuro stream de 6h", rare: 3, time: null },
  { name: "Te dedico una historia graciosa en IG", rare: 3, time: null },
  { name: "Cosplay Angel", rare: 3, time: null },
  { name: "Cosplay Chun Li", rare: 3, time: null },
  { name: "Cosplay Raven", rare: 3, time: null },
  { name: "Kigurumi Totoro", rare: 3, time: null },
  { name: "Body Sailor Moon", rare: 3, time: null },
  { name: "Body DVA", rare: 3, time: null },
  { name: "Pijama de Sanrio morada", rare: 3, time: null },
  { name: "Taiga Aisaka", rare: 3, time: null },
  { name: "Cosplay Sailor Saturno", rare: 3, time: null },
  { name: "Qipao negro", rare: 3, time: null },
  { name: "Qipao rosado", rare: 3, time: null },
  { name: "Qipao azul", rare: 3, time: null },
  { name: "Cosplay Zero Two", rare: 3, time: null },
  { name: "Cosplay Asuna", rare: 3, time: null },
  { name: "Cosplay Blancanieves", rare: 3, time: null },
  { name: "Cosplay Sage", rare: 3, time: null },
  { name: "Maquillaje de mariposa", rare: 3, time: null },
  { name: "Maquillaje de gato", rare: 3, time: null },
  { name: "Maquillaje con flores", rare: 3, time: null },
  { name: "Maquillaje de hielo", rare: 3, time: null },
  { name: "Maquillaje de fuego", rare: 3, time: null },
  { name: "Maquillaje de mimo", rare: 3, time: null },
  { name: "Maquillaje de payaso", rare: 3, time: null },
  { name: "Maquillaje de arcoíris", rare: 3, time: null },
  { name: "Maquillaje de corazones", rare: 3, time: null },
  { name: "Súmale 1h a un stream", rare: 3, time: null },
  { name: "Perreo de cabeza", rare: 3, time: null },
  { name: "Zing sin maquillaje", rare: 3, time: null },
  { name: "Zing de payaso", rare: 3, time: null },
  { name: "Zing de Cara", rare: 3, time: null },
  { name: "Selfie sin maquillaje", rare: 3, time: null },
  { name: "Baila Rasputín", rare: 3, time: null },
  { name: "Juego retro", rare: 3, time: null },
  { name: "Dibujo a lápiz", rare: 3, time: null },
  { name: "Dibujo digital", rare: 3, time: null },
  { name: "Pintura cuadro", rare: 3, time: null },
  { name: "Dibujo colores", rare: 3, time: null },
  { name: "Te hago un edit", rare: 3, time: null },
  { name: "Asmr peluquero", rare: 3, time: "1 min" },
  { name: "Rappicosplay", rare: 3, time: "1 min" },
  { name: "Imitar coreografía", rare: 3, time: null },
  { name: "Brazo zing", rare: 3, time: null },
  {
    name: "No digas la palabra 30 min - 10 sentadillas",
    rare: 3,
    time: null,
  },
  { name: "Imagen de tu elección", rare: 3, time: null },
  { name: "Dibujo a ciegas", rare: 3, time: null },
  { name: "Gato zing", rare: 3, time: null },
  { name: "UWU", rare: 3, time: null },
  { name: "Bailo la gatita con orejas", rare: 3, time: null },
  { name: "Si te ríes pierdes 3 a 5 min", rare: 3, time: null },
  { name: "Plancha", rare: 3, time: "2 min" },
  {
    name: "Pantalla fondo verde - selecciona la imagen",
    rare: 3,
    time: null,
  },
];
