export const cartas = [
  { id: 1, name: "English", rare: 1, time: "2 minutes" },
  { id: 2, name: "Jugamos Fall Guys", rare: 1, time: "1h" },
  { id: 3, name: "Jugamos Overwatch", rare: 1, time: "1h" },
  { id: 4, name: "Jugamos WZ", rare: 1, time: "1h" },
  { id: 5, name: "Jugamos Suika", rare: 1, time: "1h" },
  { id: 6, name: "Te cuento un chiste", rare: 1, time: null },
  { id: 7, name: "Te hago un piropo", rare: 1, time: null },
  { id: 8, name: "Te modelo", rare: 1, time: null },
  { id: 9, name: "10 sentadillas", rare: 1, time: null },
  { id: 10, name: "5 vueltas coreanas", rare: 1, time: null },
  { id: 11, name: "Medio shot", rare: 1, time: null },
  { id: 12, name: "Baile de TikTok", rare: 1, time: null },
  { id: 13, name: "Un baile de mochipoints", rare: 1, time: null },
  { id: 14, name: "Escoge un accesorio", rare: 1, time: null },
  { id: 15, name: "Te doy un consejo", rare: 1, time: null },

  { id: 16, name: "Haces una encuesta", rare: 1, time: null },
  { id: 17, name: "Jugamos Fortnite", rare: 1, time: "1h" },
  { id: 18, name: "Zing random", rare: 1, time: null },
  { id: 19, name: "Te hago un wallpaper", rare: 1, time: null },
  { id: 20, name: "Intento de karaoke", rare: 1, time: null },
  { id: 21, name: "Te coqueteo?", rare: 1, time: null },
  { id: 22, name: "2 verdades 1 mentira", rare: 1, time: null },
  { id: 23, name: "Horóscopo", rare: 1, time: null },
  { id: 24, name: "Escoge un tweet", rare: 1, time: null },
  { id: 25, name: "Termino las frases con una palabra", rare: 1, time: null },
  { id: 26, name: "Exagero todo", rare: 1, time: null },
  { id: 27, name: "Positivismo", rare: 1, time: "2min" },
  { id: 28, name: "Te dedico una Canción", rare: 1, time: null },
  { id: 29, name: "5 abdominales", rare: 1, time: null },
  { id: 30, name: "Mirada juzgona", rare: 1, time: null },

  { id: 31, name: "Mirada creepy", rare: 1, time: null },
  { id: 32, name: "Escoge un acento", rare: 1, time: null },
  { id: 33, name: "Jugamos kart rider", rare: 1, time: "1h" },
  { id: 34, name: "Carta caritativa", rare: 1, time: null },
  { id: 35, name: "Me automuero en el juego", rare: 1, time: null },
  { id: 36, name: "Voz vato", rare: 1, time: "2 min" },
  { id: 37, name: "Baile bombom", rare: 1, time: null },
  { id: 38, name: "Me tomo un SHOT", rare: 2, time: null },
  { id: 39, name: "English con acento paisa", rare: 2, time: "2min" },
  { id: 40, name: "Te sigo en alguna red social", rare: 2, time: null },
  { id: 41, name: "Perreo gracioso", rare: 2, time: null },
  { id: 42, name: "Canción de just dance", rare: 2, time: null },
  { id: 43, name: "Videozing", rare: 2, time: null },
  { id: 44, name: "Selfie graciosa", rare: 2, time: null },
  { id: 45, name: "Bailo YMCA", rare: 2, time: null },

  { id: 46, name: "Bailo Gangnam style", rare: 2, time: null },
  { id: 47, name: "Medio limón", rare: 2, time: null },
  { id: 48, name: "Hula Hula", rare: 2, time: "30 segundos" },
  { id: 49, name: "Pongo la quemona", rare: 2, time: null },
  { id: 50, name: "Selfie bonita para ti", rare: 2, time: null },
  { id: 51, name: "Te mando un audio bonito", rare: 2, time: null },
  { id: 52, name: "English - Con acento paisa", rare: 2, time: null },
  { id: 53, name: "Baile de los pingüinos", rare: 2, time: null },
  { id: 54, name: "30 sentadillas", rare: 2, time: null },
  { id: 55, name: "Baile kpop", rare: 2, time: null },
  { id: 56, name: "Denegar algo del juego", rare: 2, time: null },
  { id: 57, name: "Crear comando", rare: 2, time: null },
  { id: 58, name: "Jugamos xdefiant", rare: 2, time: "1h" },
  { id: 59, name: "Verdad o Reto", rare: 2, time: null },
  { id: 60, name: "Doctora corazón", rare: 2, time: null },

  { id: 61, name: "Insulto tierno", rare: 2, time: null },
  { id: 62, name: "Chismoseo tus redes sociales", rare: 2, time: null },
  { id: 63, name: "Voz kawai", rare: 2, time: "2 min" },
  { id: 64, name: "Voz ardilla", rare: 2, time: "2 min" },
  { id: 65, name: "Te hago un wallpaper", rare: 2, time: null },
  { id: 66, name: "Intento de origami", rare: 2, time: null },
  { id: 67, name: "Intento una figura en plastilina", rare: 2, time: null },
  { id: 68, name: "Juego con manos cruzadas", rare: 2, time: null },
  { id: 69, name: "Te dedico un poema", rare: 2, time: null },
  { id: 70, name: "Opinión sincera", rare: 2, time: null },
  { id: 71, name: "Ara Ara", rare: 2, time: null },
  { id: 72, name: "Fijar un mensaje", rare: 2, time: null },
  { id: 73, name: "Adivina la canción 5seg", rare: 2, time: null },
  { id: 74, name: "Juego que escojas", rare: 2, time: null },
  { id: 75, name: "Cámbiame space por letra de elección", rare: 2, time: null },

  {
    id: 76,
    name: "Actuo y hablo en camara lenta - Flash",
    rare: 2,
    time: null,
  },
  { id: 77, name: "Jugamos LOL", rare: 3, time: "1h" },
  { id: 78, name: "Te digo papacito", rare: 3, time: null },
  { id: 79, name: "Escoge un cosplay", rare: 3, time: null },
  { id: 80, name: "Te dibujo", rare: 3, time: null },
  { id: 81, name: "Futuro stream de 6h", rare: 3, time: null },
  {
    id: 82,
    name: "Te dedico una historia graciosa en IG",
    rare: 3,
    time: null,
  },
  { id: 83, name: "Cosplay Angel", rare: 3, time: null },
  { id: 84, name: "Cosplay Chun Li", rare: 3, time: null },
  { id: 85, name: "Cosplay Raven", rare: 3, time: null },
  { id: 86, name: "Kigurumi Totoro", rare: 3, time: null },
  { id: 87, name: "Body Sailor Moon", rare: 3, time: null },
  { id: 88, name: "Body DVA", rare: 3, time: null },
  { id: 89, name: "Pijama de Sanrio morada", rare: 3, time: null },
  { id: 90, name: "Taiga Aisaka", rare: 3, time: null },

  { id: 91, name: "Cosplay Sailor Saturno", rare: 3, time: null },
  { id: 92, name: "Qipao negro", rare: 3, time: null },
  { id: 93, name: "Qipao rosado", rare: 3, time: null },
  { id: 94, name: "Qipao azul", rare: 3, time: null },
  { id: 95, name: "Cosplay Zero Two", rare: 3, time: null },
  { id: 96, name: "Cosplay Asuna", rare: 3, time: null },
  { id: 97, name: "Cosplay Blancanieves", rare: 3, time: null },
  { id: 98, name: "Cosplay Sage", rare: 3, time: null },
  { id: 99, name: "Maquillaje de mariposa", rare: 3, time: null },
  { id: 100, name: "Maquillaje de gato", rare: 3, time: null },
  { id: 101, name: "Maquillaje con flores", rare: 3, time: null },
  { id: 102, name: "Maquillaje de hielo", rare: 3, time: null },
  { id: 103, name: "Maquillaje de fuego", rare: 3, time: null },
  { id: 104, name: "Maquillaje de mimo", rare: 3, time: null },
  { id: 105, name: "Maquillaje de payaso", rare: 3, time: null },

  { id: 106, name: "Maquillaje de arcoíris", rare: 3, time: null },
  { id: 107, name: "Maquillaje de corazones", rare: 3, time: null },
  { id: 108, name: "Súmale 1h a un stream", rare: 3, time: null },
  { id: 109, name: "Perreo de cabeza", rare: 3, time: null },
  { id: 110, name: "Zing sin maquillaje", rare: 3, time: null },
  { id: 111, name: "Zing de payaso", rare: 3, time: null },
  { id: 112, name: "Zing de Cara", rare: 3, time: null },
  { id: 113, name: "Selfie sin maquillaje", rare: 3, time: null },
  { id: 114, name: "Baila Rasputín", rare: 3, time: null },
  { id: 115, name: "Juego retro", rare: 3, time: null },
  { id: 116, name: "Dibujo a lápiz", rare: 3, time: null },
  { id: 117, name: "Dibujo digital", rare: 3, time: null },
  { id: 118, name: "Pintura cuadro", rare: 3, time: null },
  { id: 119, name: "Dibujo colores", rare: 3, time: null },
  { id: 120, name: "Te hago un edit", rare: 3, time: null },

  { id: 121, name: "Asmr peluquero", rare: 3, time: "1 min" },
  { id: 122, name: "Rappicosplay", rare: 3, time: "1 min" },
  { id: 123, name: "Imitar coreografía", rare: 3, time: null },
  { id: 124, name: "Brazo zing", rare: 3, time: null },
  {
    id: 125,
    name: "No digas la palabra 30 min - 10 sentadillas",
    rare: 3,
    time: null,
  },
  { id: 126, name: "Imagen de tu elección", rare: 3, time: null },
  { id: 127, name: "Dibujo a ciegas", rare: 3, time: null },
  { id: 128, name: "Gato zing", rare: 3, time: null },
  { id: 129, name: "UWU", rare: 3, time: null },
  { id: 130, name: "Bailo la gatita con orejas", rare: 3, time: null },
  { id: 131, name: "Si te ríes pierdes 3 a 5 min", rare: 3, time: null },
  { id: 132, name: "Plancha", rare: 3, time: "2 min" },
  {
    id: 133,
    name: "Pantalla fondo verde - selecciona la imagen",
    rare: 3,
    time: null,
  },
];
